backend:
  name: git-gateway
  branch: main
  # Remove base_url and auth_endpoint when using git-gateway
  # site_domain remains as the Netlify URL to identify the Identity instance
  site_domain: stellular-sundae-c9bc25.netlify.app

media_folder: "static/images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "docs"
    label: "Documentation"
    folder: "content/en/docs"
    create: true
    fields:
      - {label: "Title",       name: "title",       widget: "string"}
      - {label: "Description", name: "description", widget: "string",   required: false}
      - {label: "Date",        name: "date",        widget: "datetime", required: false}
      - {label: "Draft",       name: "draft",       widget: "boolean",  default: false}
      - {label: "Body",        name: "body",        widget: "markdown"}
