backend:
  name: github
  repo: Xer0bit/docs-idpicker
  branch: main
  auth_type: implicit
  app_id: 0v23li2Dw59A0xpVUYdp

media_folder: "static/images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "docs"
    label: "Documentation"
    folder: "content/en/docs"
    create: true
    fields:
      - {label: "Title",       name: "title",       widget: "string"}
      - {label: "Description", name: "description", widget: "string",   required: false}
      - {label: "Date",        name: "date",        widget: "datetime", required: false}
      - {label: "Draft",       name: "draft",       widget: "boolean",  default: false}
      - {label: "Body",        name: "body",        widget: "markdown"}
