backend:
  name: github
  repo: Xer0bit/docs-idpicker
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: 390a568b-294b-41bf-8384-39c3998601a1.netlify.app

media_folder: "static/images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "docs"
    label: "Documentation"
    folder: "content/en/docs"
    create: true
    fields:
      - {label: "Title",       name: "title",       widget: "string"}
      - {label: "Description", name: "description", widget: "string",   required: false}
      - {label: "Date",        name: "date",        widget: "datetime", required: false}
      - {label: "Draft",       name: "draft",       widget: "boolean",  default: false}
      - {label: "Body",        name: "body",        widget: "markdown"}
